In [ ]:
import torch

### Возможности тензоров

In [ ]:
# torch.tensor([2,3])    # получение тензора
# torch.tensor([[2, 3], [5, 6]]) #вложеный список создает двумерный тензор
# torch.tensor([[1,5], [1,5]], dtype=torch.int32)           # двумерный тензор с присвоением типа int32
# torch.tensor([[123, 453],[23, 23]], dtype=torch.float32)  # двумерный тензор с присвоением типа float32
# torch.tensor([[45,123],[54,213]], dtype=torch.float32,requires_grad=True)    # двумерный тензор с присвоением типа float32
# torch.tensor([[4,2], [5,4]], requires_grad=True) # Данный тензор не получает ошибку если не тот тип данных
# torch.tensor([[2,4], [1,3]], device=torch.device('cuda:0')) # перемещение тензора на графический процессор

tensor([[2, 4],
        [1, 3]], device='cuda:0')

### Свойства и методы tensor

In [ ]:
tensor = torch.tensor([[[2,3], [4,5]], [[6,7], [8,9]]],
                      dtype=torch.float32,
                      requires_grad=True
                      )
tensor

tensor([[[2., 3.],
         [4., 5.]],

        [[6., 7.],
         [8., 9.]]], requires_grad=True)

In [ ]:
# tensor.dtype # тип тензора --> torch.float32
# tensor.shape # размер тензора --> torch.Size([2, 2, 2])
# tensor.size() # размер тензора --> torch.Size([2, 2, 2])
# tensor.ndim # кол-во осей в тензоре --> 3

# tensor[0,0,0] # слайсинг тензора --> tensor(2., grad_fn=<SelectBackward0>)
# type(tensor[0,0,0]) # тип элемента тензора

# tensor[0,0,0].item() # вернет само число --> 2.0
type(tensor[0,0,0].item()) # вернет тип элемента --> float

float

### Создание массивов разного размера

In [ ]:
tensor = torch.zeros([2,3,2]) # создает матрицу 0, тип float32
print(tensor)
print(tensor.dtype)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])
torch.float32


In [ ]:
tensor = torch.zeros([2,3,2], dtype=torch.int32) # создает матрицу 0, тип int32
print(tensor)
print(tensor.dtype)

tensor([[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]], dtype=torch.int32)
torch.int32


In [ ]:
tensor = torch.ones([2,3,2]) # создает матрицу 1, тип float32
print(tensor)
print(tensor.dtype)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
torch.float32


In [ ]:
tensor = torch.zeros_like(tensor) # вернет тензор такого же размера, из нулей
print(tensor)
print(tensor.dtype)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])
torch.float32


In [ ]:
tensor = torch.full_like(tensor, 6) # вернет такой же тензор. заполненный указанными значениями
print(tensor)
print(tensor.dtype)

tensor([[[6., 6.],
         [6., 6.],
         [6., 6.]],

        [[6., 6.],
         [6., 6.],
         [6., 6.]]])
torch.float32


In [ ]:
torch.arange(2, 10, 0.5)

tensor([2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000, 5.5000, 6.0000,
        6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000])

In [ ]:
# диагональные матрицы
torch.diag(torch.tensor([5,8,1]))

tensor([[5, 0, 0],
        [0, 8, 0],
        [0, 0, 1]])

In [ ]:
# единичные
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
# нижнетреугольные
torch.tril(torch.tensor([[1,2,3],[4,5,6],[7,8,9]]))

tensor([[1, 0, 0],
        [4, 5, 0],
        [7, 8, 9]])

In [ ]:
# Изменение формы тензора
tensor = torch.tensor([1,2,3,4]) # --> tensor([1, 2, 3, 4])
print(tensor)

tensor_1 = tensor.view([4,1])
print(tensor_1)

tensor_2 = tensor.reshape([2,2])
print(tensor_2)

tensor([1, 2, 3, 4])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1, 2],
        [3, 4]])


In [ ]:
# добавление осей, например для первоначальной инициализации весов
print(tensor)
print(tensor.shape)

tensor = torch.unsqueeze(tensor, 0)

print(tensor)
print(tensor.shape)

tensor([1, 2, 3, 4])
torch.Size([4])
tensor([[1, 2, 3, 4]])
torch.Size([1, 4])


In [ ]:
# арифметические операции
tensor = torch.tensor([1,2,3,4,5,6],
                      dtype=torch.float32
                      )

# tensor * 5 # вернет --> tensor([ 5., 10., 15., 20., 25., 30.])
# tensor + torch.tensor([1,2,3,4,5,6]) # вернет --> tensor([ 2.,  4.,  6.,  8., 10., 12.])
# tensor + [1,2,3,4,5,6] # вернет --> TypeError: unsupported operand type(s) for +: 'Tensor' and 'list'

TypeError: unsupported operand type(s) for +: 'Tensor' and 'list'

In [ ]:
# математические операции
tensor = torch.tensor([1,2,3,4,5,6],
                      dtype=torch.float32
                      )
# tensor.sum()  # вернет --> tensor(21.)
# tensor.mean() # вернет --> tensor(3.5000)

# подсчитаем средний значения по осям тензора
tensor = tensor.view([2,3])

tensor_mean = tensor.mean(dim = 1,
                          # keepdim=True
                          )
print(tensor, end='\n\n')
print(tensor_mean)
print(tensor_mean.shape)


tensor([[1., 2., 3.],
        [4., 5., 6.]])

tensor([2., 5.])
torch.Size([2])


### Особенности PyTorch

In [ ]:
# CPU or GPU
print(torch.cpu.is_available())
print(torch.cuda.is_available())

True
True


In [ ]:
tensor = torch.tensor([1.,2.,3.], requires_grad=True)
tensor

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
# тензор по умолчанию создается на cpu
# это метод, чтобы просто его перевести на cpu
tensor = tensor.cpu()
tensor = tensor.to('cpu')
tensor

# перевод на gpu
tensor = tensor.cuda()
tensor = tensor.to('cuda')
tensor # --> tensor([1., 2., 3.], device='cuda:0', grad_fn=<ToCopyBackward0>)

tensor([1., 2., 3.], device='cuda:0', grad_fn=<ToCopyBackward0>)

In [ ]:
# удобный способ по выбору устройства для тензоров
device = 'cuda' if torch.cuda.is_available() else 'cpu'

tensor = tensor.to(device)

In [ ]:
# проверка, где находится тензор
tensor.device

device(type='cuda', index=0)

In [ ]:
tensor_1 = torch.tensor([1.,2.,3.]).to('cpu')
tensor_1.device

device(type='cpu')

In [ ]:
# теперь попробуем тензор на GPU сложить с тензором на CPU
sum_tensor = tensor + tensor_1
sum_tensor

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [ ]:
# чтобы сложить тензоры. необходимо второй перевести на GPU
tensor_1 = tensor_1.to(device)
sum_tensor = tensor + tensor_1
sum_tensor

tensor([2., 4., 6.], device='cuda:0', grad_fn=<AddBackward0>)

In [ ]:
# sum_tensor = sum_tensor.to('cpu') # --> tensor([2., 4., 6.], grad_fn=<ToCopyBackward0>)
sum_tensor = sum_tensor.cpu().detach()
sum_tensor

tensor([2., 4., 6.])